name: Build and Deploy
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.1

      - name: Install
        run: |
          make deps
          sudo apt-get install -y imagemagick
          find ./docs/assets/headshots -iname "*.png" -type f -exec bash -c 'convert "$0" -quality 90 "${0%.png}.jpeg"' {} \;

      - name: Build 🔧
        run: |
          make clean
          make jpeg
          make generate

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.0
        with:
          branch: gh-pages
          folder: docs
