name: Verify all remote addresses
on: [push]
jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4

      - name: Install
        run: |
          make deps

      - name: Build 🔧
        run: |
          make verify
